from tests.services.queue_service import *  # noqa: F401,F403
from tests.services.auth_service import *  # noqa: F401,F403
from tests.services.media_library_sync import *  # noqa: F401,F403
from tests.services.media_library_maintenance import *  # noqa: F401,F403
from tests.services.media_library_misc import *  # noqa: F401,F403
from tests.services.processing_task import *  # noqa: F401,F403
from tests.services.youtube_service import *  # noqa: F401,F403
from tests.services.lyrics_service import *  # noqa: F401,F403
from tests.services.runtime_settings import *  # noqa: F401,F403
from tests.services.demucs_client import *  # noqa: F401,F403
from tests.services.lyrics_presets import *  # noqa: F401,F403
from tests.services.default_presets import *  # noqa: F401,F403
from tests.services.stage_lobby import *  # noqa: F401,F403
from tests.services.media_trim import *  # noqa: F401,F403
from tests.services.vocal_sync import *  # noqa: F401,F403
from tests.services.lyrics_provider_loader import *  # noqa: F401,F403
from tests.services.subtitles import *  # noqa: F401,F403
from tests.services.cdg_transcode import *  # noqa: F401,F403
